[package]
name = "sayhub-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
serde = "1.0.144"
serde_derive = "1.0.144"
serde_json = "1.0.85"
dotenv = "0.15.0"
config = "0.13.2"
